### ISSUE TITLE
If zavorky

### ISSUE THREAD

**Issue by messa** [vojtechruz/pyladies-7#3]
Ahoj,

proč jsou výrazy za if v závorkách? :)

Např. tady: https://github.com/vojtechruz/pyladies-7/blob/master/soubory/domaci-ukoly/08_kostky.py

**Comment by vojtechruz** [comment]
Je to muj zlozvyk z jinych jazyku, ktere je potrebuji, pretazeny do pythonu. :) Pravdepodobne tam takovych veci bude vic.   Vecer to smazu nebo klidne udelej PR ;)

**Comment by vojtechruz** [comment]
Odstranil jsem nadbytecne zavorky

https://github.com/vojtechruz/pyladies-7/commit/82120f3fab8b0d383cf00a4b0e317bf0e84eb021

**Comment by messa** [comment]
Díky moc :)

**Comment by vojtechruz** [comment]
Neni zac :)
